version: '3.3'
services:
  postgres:
    container_name: postgres_db
    image: postgres:latest
    restart: always
    ports:
      - '5434:5432'
    environment:
      - POSTGRES_DATABASE=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: agrobank_task
    image: agrobank_task
    restart: always
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    environment:
      - PORT=${PORT}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}


volumes:
  pgdata:
